
#debug: true

spring:
# mysql数据库时的第一次运行时需要打开初始化
#    profiles:
#        include: default-user-and-roles
    jackson:
        serialization.indent_output: true
    datasource:
        url: jdbc:mysql://dbserver:3306/oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false
        name:
        username: root
        password: user123
#    datasource:
#        url: jdbc:h2:mem:oauth2;DB_CLOSE_DELAY=-1
#        name:
#        username: oauth2
#        password:
    h2:
        console:
            enabled: true
    jpa:
#        database: H2
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        generate-ddl: true
        show-sql: true
    thymeleaf:
        cache: false


logging:
  level:
    org.springframework.security: DEBUG


security:
    ignored: /resources/**, /webjars/**, /h2-console/**
